# The URL the site will be built for
base_url = "https://haochen.org"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# The site title and description; they are used in feeds by default.
title = "Chen, Hao"
description = "Professional page"

# Theme
theme = "peritus"

[extra]
# Put all your custom variables here

# Personal information
# This is used to identify and highlight my name in the author lists.
name = "Chen, Hao"
role = "Professor"
# organization = "University of California, Santa Barbara"
membership = "IEEE fellow; ACM distinguished member"
email = "hchencs@gmail.com"
cv_url = "pdf/cv.pdf"

[[extra.menu]]
name = "Publications"
url = "/publications/"
weight = 1

[[extra.menu]]
name = "Resources"
url = "/resources/"
weight = 2

[[extra.social]]
name = "Email"
url = "mailto:hchencs@gmail.com"
icon = "fas fa-envelope"

[[extra.social]]
name = "Google Scholar"
url = "https://scholar.google.com/citations?user=1Aa3qxIAAAAJ"
icon = "ai ai-google-scholar"

[[extra.social]]
name = "ORCID"
url = "https://orcid.org/0000-0002-4072-0710"
icon = "ai ai-orcid" 

# Features to enable
enable_dark_mode = true
enable_search = false

# Color theme configuration
[extra.colors]
# Light mode colors
primary_color = "#003660"
secondary_color = "#FEBC11"
accent_color = "#09847A"
text_color = "#3D4952"
background_color = "#ffffff"
card_background = "#ffffff"
border_color = "#DCE1E5"
light_background = "#EEF0F2"

# Dark mode colors
dark_text_color = "#DCE1E5"
dark_background_color = "#111517"
dark_card_background = "#1e1e1e"
dark_border_color = "#333333"
