# <customize>
# The URL the site will be built for
base_url = "https://haochen.org"
title = "JC STEM Lab of Intelligent Cybersecurity - University of Hong Kong"
description = "Our lab conducts research in computer and information security and machine learning."
# </customize>

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Theme
theme = "peritus"

[extra]
# Features to enable
enable_dark_mode = true
enable_search = false

# <customize>
# Left avatar
# avatar = ""
# Top banner
# banner = ""
# Alt text of banner
# banner_name = ""
# If unset, use the default home icon
# home_icon = ""

role = "Professor"
organization = ""
membership = "IEEE fellow; ACM distinguished member"
address = "hchencs AT gmail.com"
cv = "pdf/cv.pdf"

[extra.publication]
prefix = ""
# If author isn't empty, then highlight him/her in the author list.
author = "Chen, Hao"

[[extra.menu]]
name = "Publications"
url = "/publications/"
weight = 1

[[extra.menu]]
name = "Resources"
url = "/resources/"
weight = 2

[[extra.social]]
name = "Google Scholar"
url = "https://scholar.google.com/citations?user=1Aa3qxIAAAAJ"
icon = "ai ai-google-scholar"

[[extra.social]]
name = "ORCID"
url = "https://orcid.org/0000-0002-4072-0710"
icon = "ai ai-orcid" 

# </customize>

# Color theme configuration
[extra.colors]
# Light mode colors
primary_color = "#003660"
secondary_color = "#FEBC11"
accent_color = "#09847A"
text_color = "#3D4952"
background_color = "#ffffff"
card_background = "#ffffff"
border_color = "#DCE1E5"
light_background = "#EEF0F2"

# Dark mode colors
dark_text_color = "#DCE1E5"
dark_background_color = "#111517"
dark_card_background = "#1e1e1e"
dark_border_color = "#333333"
